"""add airlock request tables

Revision ID: 080e732ad01d
Revises: 555a167047a2
Create Date: 2026-04-25 23:02:41.398637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "080e732ad01d"
down_revision: Union[str, Sequence[str], None] = "555a167047a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "output_object_metadata",
        sa.Column("logical_object_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("researcher_justification", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("suppression_notes", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("checker_feedback", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("logical_object_id"),
    )
    op.create_table(
        "airlock_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "direction", sa.Enum("EGRESS", "INGRESS", name="airlockdirection"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "AGENT_REVIEW",
                "HUMAN_REVIEW",
                "CHANGES_REQUESTED",
                "APPROVED",
                "REJECTED",
                "RELEASING",
                "RELEASED",
                name="airlockrequeststatus",
            ),
            nullable=False,
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("submitted_by", sa.Uuid(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_airlock_requests_project_id"), "airlock_requests", ["project_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["airlock_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_timestamp"), "audit_events", ["timestamp"], unique=False)
    op.create_table(
        "output_objects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("replaces_id", sa.Uuid(), nullable=True),
        sa.Column("logical_object_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "output_type",
            sa.Enum("TABULAR", "FIGURE", "MODEL", "CODE", "REPORT", "OTHER", name="outputtype"),
            nullable=False,
        ),
        sa.Column("statbarn", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("storage_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("checksum_sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "CHANGES_REQUESTED",
                "SUPERSEDED",
                name="outputobjectstate",
            ),
            nullable=False,
        ),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["replaces_id"],
            ["output_objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["airlock_requests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_output_objects_logical_object_id"),
        "output_objects",
        ["logical_object_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_output_objects_request_id"), "output_objects", ["request_id"], unique=False
    )
    # projects.status type change skipped: SQLite doesn't support ALTER COLUMN TYPE.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_output_objects_request_id"), table_name="output_objects")
    op.drop_index(op.f("ix_output_objects_logical_object_id"), table_name="output_objects")
    op.drop_table("output_objects")
    op.drop_index(op.f("ix_audit_events_timestamp"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_airlock_requests_project_id"), table_name="airlock_requests")
    op.drop_table("airlock_requests")
    op.drop_table("output_object_metadata")
    # ### end Alembic commands ###
