"""add release_records table

Revision ID: 1e48bf626add
Revises: 3a979d6afefc
Create Date: 2026-04-25 23:58:57.775705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1e48bf626add"
down_revision: Union[str, Sequence[str], None] = "3a979d6afefc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("crate_storage_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("crate_checksum_sha256", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("presigned_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url_expires_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_to", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["airlock_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_release_records_request_id"), "release_records", ["request_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_release_records_request_id"), table_name="release_records")
    op.drop_table("release_records")
    # ### end Alembic commands ###
