"""align user and project with spec

Revision ID: 555a167047a2
Revises: 7d8d7e1827c4
Create Date: 2026-04-25 00:07:35.054031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "555a167047a2"
down_revision: Union[str, Sequence[str], None] = "7d8d7e1827c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "status",
        existing_type=sa.VARCHAR(length=9),
        type_=sa.Enum("ACTIVE", "ARCHIVED", name="projectstatus"),
        existing_nullable=False,
    )
    op.add_column(
        "users", sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("given_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("family_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("affiliation", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column(
        "users", sa.Column("crd_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    op.add_column("users", sa.Column("active", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("crd_synced_at", sa.DateTime(), nullable=False))
    op.alter_column("users", "keycloak_sub", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("users", "display_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("display_name", sa.VARCHAR(), nullable=False))
    op.alter_column("users", "keycloak_sub", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("users", "crd_synced_at")
    op.drop_column("users", "active")
    op.drop_column("users", "crd_name")
    op.drop_column("users", "affiliation")
    op.drop_column("users", "family_name")
    op.drop_column("users", "given_name")
    op.drop_column("users", "username")
    op.alter_column(
        "projects",
        "status",
        existing_type=sa.Enum("ACTIVE", "ARCHIVED", name="projectstatus"),
        type_=sa.VARCHAR(length=9),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
