"""add_ingress_delivery_tables

Revision ID: bfa6f4e6495a
Revises: 1e48bf626add
Create Date: 2026-04-26 08:02:40.950840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "bfa6f4e6495a"
down_revision: Union[str, Sequence[str], None] = "1e48bf626add"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_type", sa.Enum("WORKSPACE_PULL", name="deliverytype"), nullable=False),
        sa.Column("delivered_at", sa.DateTime(), nullable=False),
        sa.Column("delivered_by", sa.Uuid(), nullable=False),
        sa.Column("delivery_metadata", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["delivered_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["airlock_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_records_request_id"), "delivery_records", ["request_id"], unique=True
    )
    op.add_column(
        "output_objects", sa.Column("upload_url_generated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("output_objects", "upload_url_generated_at")
    op.drop_index(op.f("ix_delivery_records_request_id"), table_name="delivery_records")
    op.drop_table("delivery_records")
    # ### end Alembic commands ###
