{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "trevor.fullname" . }}-crd-reader
  labels:
    {{- include "trevor.labels" . | nindent 4 }}
rules:
  - apiGroups: ["research.karectl.io"]
    resources: ["projects"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["identity.karectl.io"]
    resources: ["groups", "users"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "trevor.fullname" . }}-crd-reader
  labels:
    {{- include "trevor.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "trevor.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "trevor.fullname" . }}-crd-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
